#c. Write a Python program to create an intersection, Union, difference of sets.
#Vrushabh Amrutiya 20CS004
st = {"lion","cat","dog","horse","cheeta"}
st2 = {"lion","cat","red","yellow","black"}
print(st|st2) # | used for finding union of elements of both sets 
print(st&st2) # & used for finding intersection of elements of both sets 
print(st-st2) # - used for finding difference of elements of both sets 